angular.module('app')
    .config(function($stateProvider,$urlRouterProvider){
        $urlRouterProvider.otherwise('index');
        $stateProvider
            .state('index',{
                url:'/index',
                templateUrl:'views/index.html'
            })
            .state('login',{
                url:'/login',
                templateUrl:'views/login.html'
            })
            .state('register',{
                url:'/register',
                templateUrl:'views/register.html'
            })
            .state('profile',{
                url:'/profile',
                templateUrl:'views/profile.html'
            })
            .state('personal',{
                url:'/personal',
                templateUrl:'views/personal.html'
            })
            .state('modify',{
                url:'/modify',
                templateUrl:'views/modify.html'
            })
            .state('social',{
                url:'/social',
                templateUrl:'views/social.html'
            })
            .state('social2',{
                url:'/social2',
                templateUrl:'views/social2.html'
            })
            .state('social3',{
                url:'/social3',
                templateUrl:'views/social3.html'
            })
            .state('news',{
                url:'/news',
                templateUrl:'views/news.html'
            })
    });